"""Add User Location Columns

Revision ID: 2d13ccd14695
Revises: 9205362ba0c2
Create Date: 2026-02-16 21:27:03.073879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d13ccd14695'
down_revision: Union[str, Sequence[str], None] = '9205362ba0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_logs_id'), table_name='plant_logs')
    op.drop_table('plant_logs')
    op.add_column('plants', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('plants', 'image_path')
    op.create_table('plant_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('health_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('plant_logs_plant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plant_logs_pkey'))
    )
    op.create_index(op.f('ix_plant_logs_id'), 'plant_logs', ['id'], unique=False)
    # ### end Alembic commands ###
